Log in on boarding screen before saving platforms
smswithoutborders/RelaySMS-Android pull request #179
Opened 2024-11-27 14:10 UTC by Idadelveloper

Fixes #168

2024-11-28 08:40 UTC, sherlockwisdom requested changes

2024-11-28 08:40 UTC, sherlockwisdom commented on app/src/main/java/com/example/sw0b_001/Onboarding/OnboardingVaultStorePlatformFragment.kt
> +                if (Vaults.fetchLongLivedToken(activity as Context).isNotBlank()) {
@Idadelveloper use requireContext() than activity as Context, activity as Context has some null risk

2024-11-28 09:53 UTC, Idadelveloper commented
This also fixes #167

2025-01-14 08:32 UTC, sherlockwisdom requested changes
The user should not be at onboarding if they have a stored token. This should be solved by figuring why the user would be able to see onboarding after reinstalling or logging out

2025-01-14 08:46 UTC, merged